# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_auto_20170913_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='user/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1'),
        ),
    ]
